name: Publish to Exchange & Deploy to CH2.0

on:
  push:
    branches: [ master, QA ]
    
jobs:         
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 8  
      
      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "${{ secrets.MAVEN_SETTINGS_BASE64 }}" | base64 --decode > ~/.m2/settings.xml

      - name: Publish to Exchange
        run: |
          mvn deploy --settings ~/.m2/settings.xml -DskipMunitTests \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mule-artifact
          path: target/*.jar

  deploy_dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        
      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "${{ secrets.MAVEN_SETTINGS_BASE64 }}" | base64 --decode > ~/.m2/settings.xml  

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: mule-artifact

      - name: Deploy to CloudHub 2.0 - Dev
        run: |
          mvn deploy --settings ~/.m2/settings.xml -DskipMunitTests -DmuleDeploy \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
          -Danypoint.businessGroup="DEV" 
  
  deploy_qa:
    needs: deploy_dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        
      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "${{ secrets.MAVEN_SETTINGS_BASE64 }}" | base64 --decode > ~/.m2/settings.xml  

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: mule-artifact

      - name: Deploy to CloudHub 2.0 - QA
        run: |
          mvn deploy --settings ~/.m2/settings.xml -DskipMunitTests -DmuleDeploy \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
          -Danypoint.businessGroup="QA" 